# Generated by Django 3.2.1 on 2021-05-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flower',
            name='slud',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
