# Generated by Django 3.2.1 on 2021-05-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210507_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='slud',
            new_name='slug',
        ),
    ]
