# Generated by Django 3.2.1 on 2021-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
