# Generated by Django 3.2.1 on 2021-05-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
